---
name: "pre-release"

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"    

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "luckym07/Pr-Review@latest"
        with:
          repo_token: "${{ vars.ACCOUNT_GITHUB_TOKEN  }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.jar
